"""Python bindings for Tetration `.tet` files and the query engine."""

from __future__ import annotations

import json
from collections.abc import Iterator, Sequence
from os import PathLike
from pathlib import Path
from typing import Any, overload

import tet._native as _native
from tet._catalog import Dataset, axes_for_query, axes_wire, dataset_from_summary
from tet._errors import (
    UnknownAxisError,
    UnknownDatasetError,
    check_query_response,
    coerce_query_doc,
)
from tet._native import CatalogError, TetError, core_version
from tet._query import (
    REDUCTION_OPS,
    QueryResult,
    op_key_from_doc,
    reduction_doc,
)

__version__: str = _native.__version__


def _parse_json_response(raw: str) -> dict[str, Any]:
    return json.loads(raw)


def _resolve_path(path: str | PathLike[str]) -> Path:
    """Expand `~` and normalize before passing paths to Rust."""
    return Path(path).expanduser()


def typing_stub(path: str | PathLike[str]) -> str:
    """Return a ``.pyi`` snippet with ``Literal`` dataset (and axis) names for one file.

    Save the output next to your code (e.g. ``mydata_tet.pyi``) so Pyright/Pylance can
    autocomplete names for that specific ``.tet`` path. Names are not known statically
    without opening the file.
    """
    with TetFile.open(path) as f:
        return f.typing_stub()


class TetFile:
    """Opened `.tet` file."""

    def __init__(self, inner: _native.TetFile) -> None:
        self._inner = inner
        self._summary_cache: dict[str, Any] | None = None

    @classmethod
    def open(cls, path: str | PathLike[str]) -> TetFile:
        """Open `.tet` read-only (same as [`tet.open`])."""
        return cls(_native.open(_resolve_path(path)))

    def __enter__(self) -> TetFile:
        return self

    def __exit__(self, *args: object) -> None:
        return None

    def __iter__(self) -> Iterator[str]:
        """Iterate dataset names (same order as the catalog)."""
        yield from self.datasets()

    def __getattr__(self, name: str) -> Any:
        return getattr(self._inner, name)

    @property
    def path(self) -> Path:
        """Resolved path to the open ``.tet`` file."""
        return Path(self._inner.path)

    @property
    def dataset_names(self) -> tuple[str, ...]:
        """Dataset names in this file (catalog order)."""
        return tuple(self.datasets())

    def typing_stub(self) -> str:
        """``.pyi`` text with ``Literal`` names from this open file (for IDE hints)."""
        lines = [
            "# Autogenerated from tet.TetFile.typing_stub() — names are per .tet file.",
            f"# source: {self.path}",
            "from __future__ import annotations",
            "from typing import Literal",
            "",
        ]
        names = self.dataset_names
        if names:
            inner = ", ".join(repr(n) for n in names)
            lines.append(f"DatasetName = Literal[{inner}]")
            lines.append("")
        for ds in self.iter_datasets():
            if ds.dim_names:
                tag = ds.name.replace("-", "_").replace(" ", "_")
                inner = ", ".join(repr(n) for n in ds.dim_names)
                lines.append(
                    f"AxisName_{tag} = Literal[{inner}]  # dim_names for {ds.name!r}"
                )
        if len(lines) == 5:
            lines.append("# (no dim_names metadata in footer for any dataset)")
        return "\n".join(lines) + "\n"

    def _summary_dict(self) -> dict[str, Any]:
        if self._summary_cache is None:
            self._summary_cache = _parse_json_response(self._inner.summary_json())
        return self._summary_cache

    def _metadata_for_dataset(self, name: str) -> dict[str, Any]:
        meta = self._summary_dict().get("metadata") or {}
        datasets = meta.get("datasets") or {}
        entry = datasets.get(name)
        return entry if isinstance(entry, dict) else {}

    def iter_datasets(self) -> Iterator[Dataset]:
        """Iterate [`Dataset`] records (name, shape, optional dim_names)."""
        for record in self._summary_dict()["datasets"]:
            name = str(record["name"])
            dim_names = self._metadata_for_dataset(name).get("dim_names")
            yield dataset_from_summary(record, dim_names)

    def _require_dataset(self, name: str) -> Dataset:
        for ds in self.iter_datasets():
            if ds.name == name:
                return ds
        raise UnknownDatasetError(
            name, path=self.path, available=self.dataset_names
        )

    def dataset(self, key: str | int) -> Dataset:
        """Look up a dataset by catalog index (0, 1, …) or name."""
        if isinstance(key, int):
            datasets = list(self.iter_datasets())
            try:
                return datasets[key]
            except IndexError as exc:
                names = self.dataset_names
                raise IndexError(
                    f"dataset index {key} out of range for {self.path} "
                    f"(count={len(datasets)}; names: {', '.join(repr(n) for n in names)})"
                ) from exc
        return self._require_dataset(key)

    def __getitem__(self, key: str | int) -> Dataset:
        """``f[0]`` or ``f['temperature']`` → [`Dataset`]."""
        return self.dataset(key)

    def summary(self) -> dict[str, Any]:
        """Catalog + footer summary (`TetFileSummaryV1`), same JSON as `tet info --json`."""
        return dict(self._summary_dict())

    def info(self) -> dict[str, Any]:
        """Alias for [`summary()`] (parity with `tet info --json`)."""
        return self.summary()

    @overload
    def query(self, query: Any, *, raw: bool = True) -> dict[str, Any]: ...

    @overload
    def query(self, query: Any, *, raw: bool = False) -> QueryResult: ...

    def query(
        self, query: Any, *, raw: bool = True
    ) -> dict[str, Any] | QueryResult:
        """Execute a query document (same as `tet query -t … -x`).

        Set ``raw=False`` for a [`QueryResult`] with ``.scalar`` / ``.reduced``
        instead of digging through ``execution.operation_*`` yourself.
        """
        doc = coerce_query_doc(query)
        if "dataset" in doc and isinstance(doc["dataset"], str):
            self._require_dataset(doc["dataset"])
        out = _parse_json_response(self._inner.query(doc))
        check_query_response(
            out,
            path=self.path,
            require_execution=op_key_from_doc(doc) is not None,
        )
        if raw:
            return out
        return QueryResult.from_response(
            out,
            op=op_key_from_doc(doc),
            path=str(self.path),
            require_execution=False,
        )

    @overload
    def query_execute(
        self,
        query: Any,
        *,
        device: str | None = None,
        raw: bool = True,
    ) -> dict[str, Any]: ...

    @overload
    def query_execute(
        self,
        query: Any,
        *,
        device: str | None = None,
        raw: bool = False,
    ) -> QueryResult: ...

    def query_execute(
        self,
        query: Any,
        *,
        device: str | None = None,
        raw: bool = True,
    ) -> dict[str, Any] | QueryResult:
        """Execute with optional ``execution.device`` (e.g. ``cpu``, ``auto``, ``cuda:0``)."""
        doc = coerce_query_doc(query)
        if device is not None:
            execution = dict(doc.get("execution") or {})
            execution["device"] = device
            doc = {**doc, "execution": execution}
        return self.query(doc, raw=raw)

    def execute(
        self,
        query: Any,
        *,
        device: str | None = None,
        raw: bool = False,
        plan: bool = False,
    ) -> dict[str, Any] | QueryResult:
        """Run a query; default is a parsed [`QueryResult`], not a JSON dump.

        Use ``plan=True`` for plan-only (no op keys). Use ``raw=True`` for the
        full wire dict (CLI / debugging).
        """
        if plan:
            return self.plan_only(query, raw=raw)
        return self.query_execute(query, device=device, raw=raw)

    @overload
    def plan_only(self, query: Any, *, raw: bool = True) -> dict[str, Any]: ...

    @overload
    def plan_only(self, query: Any, *, raw: bool = False) -> QueryResult: ...

    def plan_only(
        self, query: Any, *, raw: bool = True
    ) -> dict[str, Any] | QueryResult:
        """Plan without execution (same as `tet query` without `-x`).

        Omit ``mean`` / ``sum`` / other op keys; use only ``dataset`` (and
        optional ``selection``). For reductions, use [`query()`] or op helpers.
        """
        doc = coerce_query_doc(query)
        if "dataset" in doc and isinstance(doc["dataset"], str):
            self._require_dataset(doc["dataset"])
        out = _parse_json_response(self._inner.plan_only(doc))
        check_query_response(out, path=self.path, require_execution=False)
        if raw:
            return out
        return QueryResult.from_response(
            out, op=None, path=str(self.path), require_execution=False
        )

    def _resolve_reduction_axes(
        self,
        dataset: str,
        axes: Sequence[int | str] | None,
        *,
        axis: int | str | None,
    ) -> list[int | str]:
        if axis is not None and axes is not None:
            raise TypeError("pass only one of axes= or axis=")
        merged = axes_for_query(axes if axis is None else [axis])
        if not merged:
            return []
        self._require_dataset(dataset)
        return axes_wire(self.dataset(dataset), merged, path=self.path)

    def _reduce(
        self,
        op: str,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | int | bool | dict[str, Any] | QueryResult:
        wire_axes = self._resolve_reduction_axes(dataset, axes, axis=axis)
        doc = reduction_doc(dataset, op, wire_axes)
        if raw:
            if device is not None:
                return self.query_execute(doc, device=device, raw=True)
            return self.query(doc, raw=True)
        result = self.query_execute(doc, device=device, raw=False)
        assert isinstance(result, QueryResult)
        if wire_axes:
            return result
        if result.scalar is None:
            raise TetError(f"missing scalar for op {op!r}")
        return result.scalar

    def mean(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Mean over `dataset` (all axes, or ``axis`` / ``axes``)."""
        return self._reduce(
            "mean", dataset, axes, axis=axis, device=device, raw=raw
        )

    def sum(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Sum over `dataset` (same axis rules as [`mean()`])."""
        return self._reduce("sum", dataset, axes, axis=axis, device=device, raw=raw)

    def min(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Minimum over `dataset`."""
        return self._reduce("min", dataset, axes, axis=axis, device=device, raw=raw)

    def max(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Maximum over `dataset`."""
        return self._reduce("max", dataset, axes, axis=axis, device=device, raw=raw)

    def count(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | int | dict[str, Any] | QueryResult:
        """Element count over `dataset`."""
        return self._reduce(
            "count", dataset, axes, axis=axis, device=device, raw=raw
        )

    def std(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Population std (ddof=0) over `dataset`."""
        return self._reduce("std", dataset, axes, axis=axis, device=device, raw=raw)

    def var(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Population variance (ddof=0) over `dataset`."""
        return self._reduce("var", dataset, axes, axis=axis, device=device, raw=raw)

    def product(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Product over `dataset`."""
        return self._reduce(
            "product", dataset, axes, axis=axis, device=device, raw=raw
        )

    def norm_l1(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """L1 norm over `dataset`."""
        return self._reduce(
            "norm_l1", dataset, axes, axis=axis, device=device, raw=raw
        )

    def norm_l2(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """L2 norm (√(sum of squares)) over `dataset`."""
        return self._reduce(
            "norm_l2", dataset, axes, axis=axis, device=device, raw=raw
        )

    def median(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Median over `dataset` (materialize path in engine)."""
        return self._reduce(
            "median", dataset, axes, axis=axis, device=device, raw=raw
        )

    def all_finite(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> bool | dict[str, Any] | QueryResult:
        """True if all selected elements are finite."""
        return self._reduce(
            "all_finite", dataset, axes, axis=axis, device=device, raw=raw
        )

    def any_nan(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> bool | dict[str, Any] | QueryResult:
        """True if any selected element is NaN."""
        return self._reduce(
            "any_nan", dataset, axes, axis=axis, device=device, raw=raw
        )

    def arg_min(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> int | dict[str, Any] | QueryResult:
        """Flat index of minimum (scalar reduction over all axes)."""
        return self._reduce(
            "arg_min", dataset, axes, axis=axis, device=device, raw=raw
        )

    def arg_max(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> int | dict[str, Any] | QueryResult:
        """Flat index of maximum (scalar reduction over all axes)."""
        return self._reduce(
            "arg_max", dataset, axes, axis=axis, device=device, raw=raw
        )


def open(path: str | PathLike[str]) -> TetFile:
    return TetFile.open(path)


__all__ = [
    "CatalogError",
    "Dataset",
    "QueryResult",
    "REDUCTION_OPS",
    "TetError",
    "TetFile",
    "UnknownAxisError",
    "UnknownDatasetError",
    "__version__",
    "core_version",
    "open",
    "typing_stub",
]
