"""Opened ``.tet`` file: catalog, summary, queries, and reduction helpers.

The native mmap handle is wrapped by :class:`TetFile`; use :func:`tet.open` as the
public entry point.
"""

from __future__ import annotations

import json
from collections.abc import Iterator, Mapping, Sequence
from os import PathLike
from pathlib import Path
from typing import Any, Literal, cast, overload

import tet._native as _native
from tet._catalog import Dataset, axes_for_query, axes_wire, dataset_from_summary
from tet._errors import (
    UnknownDatasetError,
    check_query_response,
    coerce_query_doc,
)
from tet._native import TetError
from tet._query import QueryResult, reduction_doc
from tet._docstrings import _RAISE_FILE_QUERY, reduce_doc
from tet._query_doc import (
    build_query,
    correlation_op,
    covariance_op,
    histogram_op,
    null_count_op,
    op_key_from_doc,
    quantile_op,
    selection_slices,
    transform_op,
)


def _parse_json_response(raw: str) -> dict[str, Any]:
    return cast(dict[str, Any], json.loads(raw))


def _resolve_path(path: str | PathLike[str]) -> Path:
    """Expand `~` and normalize before passing paths to Rust."""
    return Path(path).expanduser()


class TetFile:
    """Read-only handle to one ``.tet`` file (catalog + query engine).

    Use :meth:`mean`, :meth:`sum`, etc. for reductions, :meth:`execute` for generic
    documents, and :meth:`dataset` / :meth:`iter_datasets` for catalog metadata.
    """

    def __init__(self, inner: _native.TetFile) -> None:
        self._inner = inner
        self._summary_cache: dict[str, Any] | None = None  # parsed summary_json()

    @classmethod
    def open(cls, path: str | PathLike[str]) -> TetFile:
        """Open a ``.tet`` file read-only via mmap.

        Parameters
        ----------
        path : str or path-like
            Filesystem path to the ``.tet`` file. ``~`` is expanded.

        Returns
        -------
        TetFile
            Handle for catalog reads and queries.

        Raises
        ------
        OSError
            If the path does not exist or cannot be opened.
        CatalogError
            If the file layout or catalog cannot be read.
        """
        return cls(_native.open(_resolve_path(path)))

    def __enter__(self) -> TetFile:
        return self

    def __exit__(self, *args: object) -> None:
        return None

    def __iter__(self) -> Iterator[str]:
        """Iterate dataset names (same order as the catalog)."""
        yield from self.datasets()

    def __getattr__(self, name: str) -> Any:
        # Forward datasets(), summary_json(), etc. from tet._native.TetFile.
        return getattr(self._inner, name)

    @property
    def path(self) -> Path:
        """Resolved path to the open ``.tet`` file."""
        return Path(self._inner.path)

    @property
    def dataset_names(self) -> tuple[str, ...]:
        """Dataset names in this file (catalog order)."""
        return tuple(self.datasets())

    def typing_stub(self) -> str:
        """Return ``.pyi`` text with ``Literal`` dataset (and axis) names for this file.

        Returns
        -------
        str
            Python source for optional IDE stubs. Save beside your code (e.g.
            ``mydata_tet.pyi``); not written automatically on :func:`tet.open`.
        """
        lines = [
            "# Autogenerated from tet.TetFile.typing_stub() — names are per .tet file.",
            f"# source: {self.path}",
            "from __future__ import annotations",
            "from typing import Literal",
            "",
        ]
        names = self.dataset_names
        if names:
            inner = ", ".join(repr(n) for n in names)
            lines.append(f"DatasetName = Literal[{inner}]")
            lines.append("")
        for ds in self.iter_datasets():
            if ds.dim_names:
                tag = ds.name.replace("-", "_").replace(" ", "_")
                inner = ", ".join(repr(n) for n in ds.dim_names)
                lines.append(
                    f"AxisName_{tag} = Literal[{inner}]  # dim_names for {ds.name!r}"
                )
        if len(lines) == 5:
            lines.append("# (no dim_names metadata in footer for any dataset)")
        return "\n".join(lines) + "\n"

    def _summary_dict(self) -> dict[str, Any]:
        """Cached ``TetFileSummaryV1`` dict from Rust (same as :meth:`summary`)."""
        if self._summary_cache is None:
            self._summary_cache = _parse_json_response(self._inner.summary_json())
        return self._summary_cache

    def _metadata_for_dataset(self, name: str) -> dict[str, Any]:
        meta = self._summary_dict().get("metadata") or {}
        datasets = meta.get("datasets") or {}
        entry = datasets.get(name)
        return entry if isinstance(entry, dict) else {}

    def iter_datasets(self) -> Iterator[Dataset]:
        """Iterate [`Dataset`] records (name, shape, optional dim_names)."""
        for record in self._summary_dict()["datasets"]:
            name = str(record["name"])
            dim_names = self._metadata_for_dataset(name).get("dim_names")
            yield dataset_from_summary(record, dim_names)

    def _require_dataset(self, name: str) -> Dataset:
        """Resolve ``name`` or raise :class:`~tet.UnknownDatasetError` before query."""
        for ds in self.iter_datasets():
            if ds.name == name:
                return ds
        raise UnknownDatasetError(name, path=self.path, available=self.dataset_names)

    def dataset(self, key: str | int) -> Dataset:
        """Look up one dataset by catalog index or name.

        Parameters
        ----------
        key : str or int
            Dataset name, or catalog index ``0``, ``1``, … (same order as :meth:`iter_datasets`).

        Returns
        -------
        Dataset
            Shape, dtype tag, chunk_shape, and optional ``dim_names``.

        Raises
        ------
        UnknownDatasetError
            If ``key`` is a string name not in this file.
        IndexError
            If ``key`` is an integer index out of range.
        """
        if isinstance(key, int):
            datasets = list(self.iter_datasets())
            try:
                return datasets[key]
            except IndexError as exc:
                names = self.dataset_names
                raise IndexError(
                    f"dataset index {key} out of range for {self.path} "
                    f"(count={len(datasets)}; names: {', '.join(repr(n) for n in names)})"
                ) from exc
        return self._require_dataset(key)

    def __getitem__(self, key: str | int) -> Dataset:
        """``f[0]`` or ``f['temperature']`` → [`Dataset`]."""
        return self.dataset(key)

    def summary(self) -> dict[str, Any]:
        """Return the full catalog summary for this file.

        Returns
        -------
        dict
            ``TetFileSummaryV1`` JSON: ``superblock``, ``datasets``, ``chunks``,
            ``file_execution``, ``history``, ``metadata``. Same as ``tet info --json``.
        """
        return dict(self._summary_dict())

    def info(self) -> dict[str, Any]:
        """Alias for :meth:`summary` (includes every chunk index row)."""
        return self.summary()

    @overload
    def query(self, query: Any, *, raw: Literal[True]) -> dict[str, Any]: ...

    @overload
    def query(self, query: Any, *, raw: Literal[False]) -> QueryResult: ...

    def query(self, query: Any, *, raw: bool = True) -> dict[str, Any] | QueryResult:
        f"""Execute a query document (``tet query -t file.tet -x``).

        Parameters
        ----------
        query : dict or str
            Query document (dict) or JSON string. Must include ``"dataset"`` and one op key
            (e.g. ``"mean": []``) unless planning only via :meth:`plan_only`.
        raw : bool, default True
            If True, return the full ``QueryResponse`` dict. If False, return :class:`~tet.QueryResult`.

        Returns
        -------
        dict or QueryResult
            Wire JSON when ``raw=True``; parsed result with ``.scalar`` / ``.reduced`` when ``raw=False``.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        """
        doc = coerce_query_doc(query)
        if "dataset" in doc and isinstance(doc["dataset"], str):
            self._require_dataset(doc["dataset"])
        out = _parse_json_response(self._inner.query(doc))
        check_query_response(
            out,
            path=self.path,
            require_execution=op_key_from_doc(doc) is not None,
        )
        if raw:
            return out
        return QueryResult.from_response(
            out,
            op=op_key_from_doc(doc),
            path=str(self.path),
            require_execution=False,
        )

    @overload
    def query_execute(
        self,
        query: Any,
        *,
        device: str | None = None,
        raw: Literal[True] = True,
    ) -> dict[str, Any]: ...

    @overload
    def query_execute(
        self,
        query: Any,
        *,
        device: str | None = None,
        raw: Literal[False],
    ) -> QueryResult: ...

    def query_execute(
        self,
        query: Any,
        *,
        device: str | None = None,
        raw: bool = True,
    ) -> dict[str, Any] | QueryResult:
        f"""Like :meth:`query`, with optional ``execution.device``.

        Parameters
        ----------
        query : dict or str
            Query document (see :meth:`query`).
        device : str, optional
            Written to ``execution.device`` before execute (e.g. ``"cpu"``).
        raw : bool, default True
            Same as :meth:`query`.

        Returns
        -------
        dict or QueryResult
            Same as :meth:`query`.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        """
        doc = coerce_query_doc(query)
        if device is not None:
            execution = dict(doc.get("execution") or {})
            execution["device"] = device
            doc = {**doc, "execution": execution}
        if raw:
            return self.query(doc, raw=True)
        return self.query(doc, raw=False)

    def execute(
        self,
        query: Any,
        *,
        device: str | None = None,
        raw: bool = False,
        plan: bool = False,
    ) -> dict[str, Any] | QueryResult:
        f"""Run or plan a query; default return is :class:`~tet.QueryResult` (``raw=False``).

        Parameters
        ----------
        query : dict or str
            Query document (see :meth:`query`).
        device : str, optional
            Passed to :meth:`query_execute` when executing.
        raw : bool, default False
            If True, return wire ``dict``; if False, return :class:`~tet.QueryResult`.
        plan : bool, default False
            If True, call :meth:`plan_only` (no op keys; no ``execution`` block).

        Returns
        -------
        dict or QueryResult
            Plan or execute result depending on ``plan`` and ``raw``.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        """
        if plan:
            if raw:
                return self.plan_only(query, raw=True)
            return self.plan_only(query, raw=False)
        if raw:
            return self.query_execute(query, device=device, raw=True)
        return self.query_execute(query, device=device, raw=False)

    @overload
    def plan_only(self, query: Any, *, raw: Literal[True]) -> dict[str, Any]: ...

    @overload
    def plan_only(self, query: Any, *, raw: Literal[False]) -> QueryResult: ...

    def plan_only(
        self, query: Any, *, raw: bool = True
    ) -> dict[str, Any] | QueryResult:
        f"""Plan a query without executing (``tet query`` without ``-x``).

        Parameters
        ----------
        query : dict or str
            Document with ``"dataset"`` and optional ``"selection"`` only (no ``mean``/``sum``/…).
        raw : bool, default True
            If True, wire ``dict``; if False, :class:`~tet.QueryResult` (typically no ``.scalar``).

        Returns
        -------
        dict or QueryResult
            Response with plan/catalog fields; ``execution`` is usually absent.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        """
        doc = coerce_query_doc(query)
        if "dataset" in doc and isinstance(doc["dataset"], str):
            self._require_dataset(doc["dataset"])
        out = _parse_json_response(self._inner.plan_only(doc))
        check_query_response(out, path=self.path, require_execution=False)
        if raw:
            return out
        return QueryResult.from_response(
            out, op=None, path=str(self.path), require_execution=False
        )

    def _resolve_reduction_axes(
        self,
        dataset: str,
        axes: Sequence[int | str] | None,
        *,
        axis: int | str | None,
    ) -> list[int | str]:
        """Wire axis list for list-style ops; ``[]`` means reduce all dimensions."""
        if axis is not None and axes is not None:
            raise TypeError("pass only one of axes= or axis=")
        merged = axes_for_query(axes if axis is None else [axis])
        if not merged:
            return []
        self._require_dataset(dataset)
        return axes_wire(self.dataset(dataset), merged, path=self.path)

    def _execute_doc(
        self,
        doc: dict[str, Any],
        *,
        device: str | None = None,
        raw: bool = False,
        scalar_op: str | None = None,
    ) -> float | list[float] | dict[str, Any] | QueryResult:
        """Run a built document; unwrap scalars when ``scalar_op`` is set."""
        if raw:
            if device is not None:
                return self.query_execute(doc, device=device, raw=True)
            return self.query(doc, raw=True)
        result = self.query_execute(doc, device=device, raw=False)
        assert isinstance(result, QueryResult)
        if scalar_op and result.scalar is not None:
            return result.scalar
        if scalar_op in ("histogram", "covariance", "correlation", "transform"):
            return result
        if scalar_op and result.reduced is not None:
            return result
        return result

    def _reduce(
        self,
        op: str,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | int | bool | dict[str, Any] | QueryResult:
        """Shared path for ``mean`` / ``sum`` / ``min`` / … list-style reductions."""
        wire_axes = self._resolve_reduction_axes(dataset, axes, axis=axis)
        doc = reduction_doc(dataset, op, wire_axes)
        if raw:
            if device is not None:
                return self.query_execute(doc, device=device, raw=True)
            return self.query(doc, raw=True)
        result = self.query_execute(doc, device=device, raw=False)
        assert isinstance(result, QueryResult)
        if wire_axes:
            return result
        if result.scalar is None:
            raise TetError(f"missing scalar for op {op!r}")
        return result.scalar

    def mean(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Mean over ``dataset`` (all axes, or ``axis`` / ``axes``)."""
        return self._reduce("mean", dataset, axes, axis=axis, device=device, raw=raw)

    def sum(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Sum over ``dataset`` (same axis rules as :meth:`mean`)."""
        return self._reduce("sum", dataset, axes, axis=axis, device=device, raw=raw)

    def min(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Minimum over `dataset`."""
        return self._reduce("min", dataset, axes, axis=axis, device=device, raw=raw)

    def max(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Maximum over `dataset`."""
        return self._reduce("max", dataset, axes, axis=axis, device=device, raw=raw)

    def count(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | int | dict[str, Any] | QueryResult:
        """Element count over `dataset`."""
        return self._reduce("count", dataset, axes, axis=axis, device=device, raw=raw)

    def numel(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | int | dict[str, Any] | QueryResult:
        f"""Number of elements (NumPy ``size`` semantics).

        Calls :meth:`count` internally — wire query op is ``"count"``, not ``numel``.
        Python name only; CLI / :func:`build_query` still use ``count=[]``.

        Parameters
        ----------
        dataset, axes, axis, device, raw
            Same as :meth:`count`.

        Returns
        -------
        float, int, QueryResult, or dict
            Same as :meth:`count`.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        """
        return self.count(dataset, axes, axis=axis, device=device, raw=raw)

    def std(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Population std (ddof=0) over `dataset`."""
        return self._reduce("std", dataset, axes, axis=axis, device=device, raw=raw)

    def var(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Population variance (ddof=0) over `dataset`."""
        return self._reduce("var", dataset, axes, axis=axis, device=device, raw=raw)

    def product(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Product over `dataset`."""
        return self._reduce("product", dataset, axes, axis=axis, device=device, raw=raw)

    def norm_l1(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """L1 norm over `dataset`."""
        return self._reduce("norm_l1", dataset, axes, axis=axis, device=device, raw=raw)

    def norm_l2(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """L2 norm (√(sum of squares)) over `dataset`."""
        return self._reduce("norm_l2", dataset, axes, axis=axis, device=device, raw=raw)

    def median(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Median over `dataset` (materialize path in engine)."""
        return self._reduce("median", dataset, axes, axis=axis, device=device, raw=raw)

    def all_finite(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> bool | dict[str, Any] | QueryResult:
        """True if all selected elements are finite."""
        return cast(
            bool,
            self._reduce(
                "all_finite", dataset, axes, axis=axis, device=device, raw=raw
            ),
        )

    def any_nan(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> bool | dict[str, Any] | QueryResult:
        """True if any selected element is NaN."""
        return cast(
            bool,
            self._reduce("any_nan", dataset, axes, axis=axis, device=device, raw=raw),
        )

    def arg_min(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> int | dict[str, Any] | QueryResult:
        """Flat index of minimum (scalar reduction over all axes)."""
        return cast(
            int,
            self._reduce("arg_min", dataset, axes, axis=axis, device=device, raw=raw),
        )

    def arg_max(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> int | dict[str, Any] | QueryResult:
        """Flat index of maximum (scalar reduction over all axes)."""
        return cast(
            int,
            self._reduce("arg_max", dataset, axes, axis=axis, device=device, raw=raw),
        )

    def any_inf(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> bool | dict[str, Any] | QueryResult:
        """True if any selected element is ±infinity."""
        return cast(
            bool,
            self._reduce("any_inf", dataset, axes, axis=axis, device=device, raw=raw),
        )

    def nan_count(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> int | float | dict[str, Any] | QueryResult:
        """Count of NaN elements in the selection."""
        return cast(
            int | float,
            self._reduce(
                "nan_count", dataset, axes, axis=axis, device=device, raw=raw
            ),
        )

    def inf_count(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> int | float | dict[str, Any] | QueryResult:
        """Count of ±infinity elements in the selection."""
        return cast(
            int | float,
            self._reduce(
                "inf_count", dataset, axes, axis=axis, device=device, raw=raw
            ),
        )

    def null_count(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        fill: float | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> int | float | dict[str, Any] | QueryResult:
        f"""Count of fill-missing values (``_FillValue`` / attrs when ``fill`` omitted).

        Parameters
        ----------
        dataset : str
            Catalog dataset name.
        axes, axis : optional
            Same as :meth:`mean`.
        fill : float, optional
            Explicit fill value; otherwise resolved from dataset footer attrs.
        device, raw : optional
            Same as :meth:`mean`.

        Returns
        -------
        int, float, QueryResult, or dict
            Element count when fully reduced and ``raw=False``; else :class:`~tet.QueryResult`.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        """
        ds = self.dataset(dataset)
        wire = null_count_op(ds, axes, axis=axis, fill=fill, path=str(self.path))
        doc = build_query(dataset, null_count=wire)
        out = self._execute_doc(doc, device=device, raw=raw, scalar_op="null_count")
        assert isinstance(out, (int, float, dict, QueryResult))
        return out

    def nan_mean(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Mean over finite elements (NaN-skipping)."""
        return self._reduce(
            "nan_mean", dataset, axes, axis=axis, device=device, raw=raw
        )

    def nan_std(
        self,
        dataset: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        """Population std over finite elements (NaN-skipping, ddof=0)."""
        return self._reduce(
            "nan_std", dataset, axes, axis=axis, device=device, raw=raw
        )

    def quantile(
        self,
        dataset: str,
        q: float,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        selection: Sequence[Mapping[str, Any]] | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> float | dict[str, Any] | QueryResult:
        f"""Quantile over a dataset.

        Parameters
        ----------
        dataset : str
            Catalog dataset name.
        q : float
            Quantile in ``[0, 1]`` (e.g. ``0.5`` for median).
        axes, axis : optional
            Same as :meth:`mean`.
        selection : sequence of dict, optional
            Per-axis slices (see :func:`~tet.selection_slices`).
        device, raw : optional
            Same as :meth:`mean`.

        Returns
        -------
        float, QueryResult, or dict
            Scalar quantile when ``raw=False`` and full reduction; else :class:`~tet.QueryResult` or wire dict.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        """
        ds = self.dataset(dataset)
        doc = build_query(
            dataset,
            selection=selection,
            quantile=quantile_op(
                ds, q, axes, axis=axis, path=str(self.path)
            ),
        )
        out = self._execute_doc(doc, device=device, raw=raw, scalar_op="quantile")
        assert isinstance(out, (float, dict, QueryResult))
        return out

    def histogram(
        self,
        dataset: str,
        bins: int,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        min: float | None = None,
        max: float | None = None,
        selection: Sequence[Mapping[str, Any]] | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> QueryResult | dict[str, Any]:
        f"""Histogram over a dataset.

        Parameters
        ----------
        dataset : str
            Catalog dataset name.
        bins : int
            Number of histogram buckets.
        axes, axis, min, max : optional
            Axes to reduce; optional value range clamp.
        selection, device, raw : optional
            Same as :meth:`quantile`.

        Returns
        -------
        QueryResult or dict
            ``QueryResult`` with ``.histogram_counts`` / ``.histogram_edges`` when ``raw=False``.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        """
        ds = self.dataset(dataset)
        doc = build_query(
            dataset,
            selection=selection,
            histogram=histogram_op(
                ds, bins, axes, axis=axis, min=min, max=max, path=str(self.path)
            ),
        )
        out = self._execute_doc(doc, device=device, raw=raw, scalar_op="histogram")
        assert isinstance(out, (dict, QueryResult))
        return out

    def covariance(
        self,
        dataset: str,
        axis: int | str,
        *,
        selection: Sequence[Mapping[str, Any]] | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> QueryResult | dict[str, Any]:
        f"""Population covariance matrix (rank-2 dataset).

        Parameters
        ----------
        dataset : str
            Catalog dataset name (must be 2-D).
        axis : int or str
            Observation axis (variables along the other axis).
        selection, device, raw : optional
            Subregion and execution options.

        Returns
        -------
        QueryResult or dict
            ``QueryResult`` with ``.matrix`` (row-major ``order×order``) and ``.matrix_order``.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        """
        ds = self.dataset(dataset)
        doc = build_query(
            dataset,
            selection=selection,
            covariance=covariance_op(ds, axis, path=str(self.path)),
        )
        out = self._execute_doc(doc, device=device, raw=raw, scalar_op="covariance")
        assert isinstance(out, (dict, QueryResult))
        return out

    def correlation(
        self,
        dataset: str,
        axis: int | str,
        *,
        selection: Sequence[Mapping[str, Any]] | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> QueryResult | dict[str, Any]:
        f"""Pearson correlation matrix (rank-2 dataset).

        Parameters
        ----------
        dataset : str
            Catalog dataset name (must be 2-D).
        axis : int or str
            Observation axis.
        selection, device, raw : optional
            Same as :meth:`covariance`.

        Returns
        -------
        QueryResult or dict
            ``QueryResult`` with ``.matrix`` and ``.matrix_order``.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        """
        ds = self.dataset(dataset)
        doc = build_query(
            dataset,
            selection=selection,
            correlation=correlation_op(ds, axis, path=str(self.path)),
        )
        out = self._execute_doc(
            doc, device=device, raw=raw, scalar_op="correlation"
        )
        assert isinstance(out, (dict, QueryResult))
        return out

    def transform(
        self,
        dataset: str,
        method: str,
        axes: Sequence[int | str] | None = None,
        *,
        axis: int | str | None = None,
        write: str | Mapping[str, Any] | None = "switch",
        selection: Sequence[Mapping[str, Any]] | None = None,
        device: str | None = None,
        raw: bool = False,
    ) -> QueryResult | dict[str, Any]:
        f"""Shape-preserving transform (two-pass; pass-1 stats in ``execution``).

        Parameters
        ----------
        dataset : str
            Catalog dataset name.
        method : str
            One of ``zscore``, ``minmax``, ``l1``, ``l2``, ``center``, ``scale``,
            ``log1p``, ``sqrt``, ``softmax``.
        axes, axis : optional
            Axes to fold per-cell stats; omit for one global stat set.
        write : str or dict, default ``"switch"``
            Output routing: ``"switch"`` (RAM or spill by budget), ``"ram"``, ``"spill"``,
            or ``{{"target": "spill", "path": "out.bin"}}``.
        selection, device, raw : optional
            Same as :meth:`quantile`.

        Returns
        -------
        QueryResult or dict
            Pass-1 fold stats in ``.execution`` / ``.raw``; preview arrays when present.

        Raises
        ------
        {_RAISE_FILE_QUERY}
        ValueError
            If ``method`` is not a known transform token.
        """
        ds = self.dataset(dataset)
        doc = build_query(
            dataset,
            selection=selection,
            transform=transform_op(
                ds, method, axes, axis=axis, path=str(self.path)
            ),
        )
        if write is not None:
            doc["write"] = write
        out = self._execute_doc(doc, device=device, raw=raw, scalar_op="transform")
        assert isinstance(out, (dict, QueryResult))
        return out


_REDUCE_METHODS: dict[str, str] = {
    "mean": "Arithmetic mean.",
    "sum": "Sum of elements.",
    "min": "Minimum value.",
    "max": "Maximum value.",
    "count": "Element count.",
    "std": "Population standard deviation (ddof=0).",
    "var": "Population variance (ddof=0).",
    "product": "Product of elements.",
    "norm_l1": "L1 norm.",
    "norm_l2": "L2 norm (sqrt of sum of squares).",
    "median": "Median (materializes full selection).",
    "all_finite": "Whether all elements are finite.",
    "any_nan": "Whether any element is NaN.",
    "any_inf": "Whether any element is ±infinity.",
    "nan_count": "Count of NaN elements.",
    "inf_count": "Count of ±infinity elements.",
    "null_count": "Count of fill-missing values.",
    "nan_mean": "Mean over finite elements (NaN-skipping).",
    "nan_std": "Population std over finite elements (NaN-skipping, ddof=0).",
    "arg_min": "Flat index of minimum (all axes reduced).",
    "arg_max": "Flat index of maximum (all axes reduced).",
}

for _name, _summary in _REDUCE_METHODS.items():
    getattr(TetFile, _name).__doc__ = reduce_doc(_summary)
