from pathlib import Path
from typing import Any

import numpy as np

__version__: str

class TetError(Exception): ...
class CatalogError(Exception): ...

class TetFile:
    @property
    def path(self) -> str: ...
    def datasets(self) -> list[str]: ...
    def summary_json(self) -> str: ...
    def query(self, query: Any, preview_max: int | None = None) -> str: ...
    def plan_only(self, query: Any) -> str: ...
    def read_numpy(self, query: Any) -> np.ndarray: ...
    def transform_to_numpy(self, query: Any) -> np.ndarray: ...

class WriteDatasetOptions:
    def __init__(self) -> None: ...
    chunk_shape: tuple[int, ...] | None
    attrs: dict[str, str] | None
    dim_names: list[str] | None
    coords: dict[str, list[str]] | None

class TetWriterSession:
    @staticmethod
    def create(path: Path) -> TetWriterSession: ...
    @staticmethod
    def open_append(path: Path) -> TetWriterSession: ...
    @property
    def path(self) -> str: ...
    @property
    def dataset_count(self) -> int: ...
    def write_dataset(
        self,
        name: str,
        array: np.ndarray,
        options: WriteDatasetOptions | None = None,
    ) -> None: ...
    def push_history_event(self, op: str, source: str) -> None: ...
    def commit(self) -> str: ...

def open(path: Path) -> TetFile: ...
def core_version() -> str: ...
