from pathlib import Path
from typing import Any

__version__: str

class TetError(Exception): ...
class CatalogError(Exception): ...

class TetFile:
    @property
    def path(self) -> str: ...
    def datasets(self) -> list[str]: ...
    def summary_json(self) -> str: ...
    def query(self, query: Any) -> str: ...
    def plan_only(self, query: Any) -> str: ...

def open(path: Path) -> TetFile: ...
def core_version() -> str: ...
